"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useContextActions, useContextState } from "@/context/GlobalContext";
import AnthropicKeyPanel from "@/components/AnthropicKeyPanel";
import ChatStream from "@/components/ChatStream";
import DocumentUpload from "@/components/DocumentUpload";
import ProviderPicker from "@/components/ProviderPicker";
import SignIn from "@/components/SignIn";
import SourcePanel from "@/components/SourcePanel";
import ToolTrace from "@/components/ToolTrace";
import type { SourceChunk, ToolRun } from "@/lib/types";

export default function Home() {
  // Everything shared with the rest of the app comes from the store: whether we are signed
  // in, the provider catalogue, and which provider and model the reader chose. Only what
  // belongs to *this page* stays local — the sources and the tool trace are panels beside
  // the answer, not facts about the app.
  const { signedIn, providers } = useContextState();
  const { checkSession, loadProviders, setProvider, setModel, signOut } =
    useContextActions();

  const [sources, setSources] = useState<SourceChunk[]>([]);
  const [toolRuns, setToolRuns] = useState<ToolRun[]>([]);

  useEffect(() => {
    void checkSession();
  }, [checkSession]);

  useEffect(() => {
    if (signedIn && !providers.loaded) void loadProviders();
  }, [signedIn, providers.loaded, loadProviders]);

  if (signedIn === null) {
    return (
      <div className="shell">
        <p className="empty">Loading…</p>
      </div>
    );
  }

  if (!signedIn) {
    return (
      <div className="shell">
        <header className="masthead">
          <div>
            <h1>mcp-py</h1>
            <div className="sub">LLM · RAG · MCP showcase</div>
          </div>
        </header>
        <SignIn onSignedIn={() => void checkSession()} />
      </div>
    );
  }

  return (
    <div className="shell">
      <header className="masthead">
        <div>
          <h1>mcp-py</h1>
          <div className="sub">
            Local SQLite vectors · answer generated by your chosen provider
          </div>
        </div>
        <nav className="tutor-nav">
          <Link href="/" className="active">
            Documents
          </Link>
          <Link href="/tutor">Tutor</Link>
          <Link href="/status">Status</Link>
        </nav>

        <button className="secondary" onClick={() => void signOut()}>
          Sign out
        </button>
      </header>

      <div className="layout">
        <div>
          <ChatStream onSources={setSources} onToolRuns={setToolRuns} />
          <SourcePanel chunks={sources} />
          <ToolTrace runs={toolRuns} />
        </div>

        <aside>
          <ProviderPicker
            providers={providers.data}
            provider={providers.provider}
            model={providers.model}
            onProviderChange={setProvider}
            onModelChange={setModel}
          />
          {/* Adding or removing a key changes which providers are usable, so
              reload the picker rather than leaving it stale. */}
          <AnthropicKeyPanel onChanged={() => void loadProviders()} />
          <DocumentUpload signedIn={signedIn} />
        </aside>
      </div>
    </div>
  );
}
