"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import ChatStream from "@/components/ChatStream";
import DocumentUpload from "@/components/DocumentUpload";
import ProviderPicker from "@/components/ProviderPicker";
import SignIn from "@/components/SignIn";
import SourcePanel from "@/components/SourcePanel";
import ToolTrace from "@/components/ToolTrace";
import type { ProvidersPayload, SourceChunk, ToolRun } from "@/lib/types";

export default function Home() {
  const [signedIn, setSignedIn] = useState<boolean | null>(null);
  const [providers, setProviders] = useState<ProvidersPayload | null>(null);
  const [provider, setProvider] = useState("ollama");
  const [model, setModel] = useState("");
  const [sources, setSources] = useState<SourceChunk[]>([]);
  const [toolRuns, setToolRuns] = useState<ToolRun[]>([]);

  useEffect(() => {
    void fetch("/api/auth")
      .then((r) => r.json())
      .then((b: { signedIn: boolean }) => setSignedIn(b.signedIn))
      .catch(() => setSignedIn(false));
  }, []);

  const loadProviders = useCallback(async () => {
    const response = await fetch("/api/providers");
    if (!response.ok) return;
    const body = (await response.json()) as ProvidersPayload;
    setProviders(body);

    // Prefer the backend default, but fall back to whichever provider is
    // actually usable — so the picker is never stuck on a dead option.
    const preferred =
      body.data.find((p) => p.name === body.default_provider && p.available) ??
      body.data.find((p) => p.available);
    if (preferred) {
      setProvider(preferred.name);
      setModel(preferred.default_model);
    }
  }, []);

  useEffect(() => {
    if (signedIn) void loadProviders();
  }, [signedIn, loadProviders]);

  async function signOut() {
    await fetch("/api/auth", { method: "DELETE" });
    setSignedIn(false);
    setProviders(null);
  }

  if (signedIn === null) {
    return (
      <div className="shell">
        <p className="empty">Loading…</p>
      </div>
    );
  }

  if (!signedIn) {
    return (
      <div className="shell">
        <header className="masthead">
          <div>
            <h1>mcp-py</h1>
            <div className="sub">LLM · RAG · MCP showcase</div>
          </div>
        </header>
        <SignIn onSignedIn={() => setSignedIn(true)} />
      </div>
    );
  }

  return (
    <div className="shell">
      <header className="masthead">
        <div>
          <h1>mcp-py</h1>
          <div className="sub">
            Local SQLite vectors · answer generated by your chosen provider
          </div>
        </div>
        <nav className="tutor-nav">
          <Link href="/" className="active">
            Documents
          </Link>
          <Link href="/tutor">Tutor</Link>
        </nav>

        <button className="secondary" onClick={signOut}>
          Sign out
        </button>
      </header>

      <div className="layout">
        <div>
          <ChatStream
            provider={provider}
            model={model}
            onSources={setSources}
            onToolRuns={setToolRuns}
          />
          <SourcePanel chunks={sources} />
          <ToolTrace runs={toolRuns} />
        </div>

        <aside>
          <ProviderPicker
            providers={providers}
            provider={provider}
            model={model}
            onProviderChange={setProvider}
            onModelChange={setModel}
          />
          <DocumentUpload signedIn={signedIn} />
        </aside>
      </div>
    </div>
  );
}
